// <auto-generated />
using System;
using DataAccessLayer.Concrete;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DataAccessLayer.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240604225709_mig1")]
    partial class mig1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EntityLayer.Concrete.Adresses", b =>
                {
                    b.Property<int?>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int?>("id"));

                    b.Property<string>("actie")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("adresses")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("city_id")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("distirct_id")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("Adresses");
                });

            modelBuilder.Entity("EntityLayer.Concrete.Categories", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<int?>("Usersid")
                        .HasColumnType("int");

                    b.Property<int?>("competence_id")
                        .HasColumnType("int");

                    b.Property<string>("name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.HasIndex("Usersid");

                    b.HasIndex("competence_id");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("EntityLayer.Concrete.Companies", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<int?>("address_id")
                        .HasColumnType("int");

                    b.Property<string>("company_title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("explanation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("fax_phone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("logo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("mail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("phone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("tax_no")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.HasIndex("address_id");

                    b.ToTable("Companies");
                });

            modelBuilder.Entity("EntityLayer.Concrete.Competencies", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<int?>("job_id")
                        .HasColumnType("int");

                    b.Property<string>("name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.HasIndex("job_id");

                    b.ToTable("Competencies");
                });

            modelBuilder.Entity("EntityLayer.Concrete.JobAdverts", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("Department")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EducationLevel")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Experience")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("JobLocation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Level")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MilitaryStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Position")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("advert_end_date")
                        .HasColumnType("datetime2");

                    b.Property<int?>("company_id")
                        .HasColumnType("int");

                    b.Property<string>("description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("type_of_work")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.HasIndex("company_id");

                    b.ToTable("JobAdverts");
                });

            modelBuilder.Entity("EntityLayer.Concrete.JobApplications", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<DateTime?>("job_app_date")
                        .HasColumnType("datetime2");

                    b.Property<int?>("job_id")
                        .HasColumnType("int");

                    b.Property<int?>("user_id")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("job_id");

                    b.HasIndex("user_id");

                    b.ToTable("JobApplications");
                });

            modelBuilder.Entity("EntityLayer.Concrete.JobSkills", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<int?>("Usersid")
                        .HasColumnType("int");

                    b.Property<int?>("category_id")
                        .HasColumnType("int");

                    b.Property<int?>("compet_id")
                        .HasColumnType("int");

                    b.Property<int?>("job_type_id")
                        .HasColumnType("int");

                    b.Property<int?>("jobadvert_id")
                        .HasColumnType("int");

                    b.Property<string>("level")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("max_level_score")
                        .HasColumnType("int");

                    b.Property<int>("min_level_score")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("Usersid");

                    b.HasIndex("category_id");

                    b.HasIndex("compet_id");

                    b.HasIndex("job_type_id");

                    b.HasIndex("jobadvert_id");

                    b.ToTable("JobSkills");
                });

            modelBuilder.Entity("EntityLayer.Concrete.JobTypes", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<int?>("Usersid")
                        .HasColumnType("int");

                    b.Property<string>("name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.HasIndex("Usersid");

                    b.ToTable("JobTypes");
                });

            modelBuilder.Entity("EntityLayer.Concrete.UserSkills", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<int?>("Beg")
                        .HasColumnType("int");

                    b.Property<int?>("Exper")
                        .HasColumnType("int");

                    b.Property<int?>("Expert")
                        .HasColumnType("int");

                    b.Property<int?>("Ju")
                        .HasColumnType("int");

                    b.Property<int?>("Mid")
                        .HasColumnType("int");

                    b.Property<int?>("category_id")
                        .HasColumnType("int");

                    b.Property<int?>("compet_id")
                        .HasColumnType("int");

                    b.Property<int?>("job_type_id")
                        .HasColumnType("int");

                    b.Property<string>("level")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("level_score")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("user_id")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("category_id");

                    b.HasIndex("compet_id");

                    b.HasIndex("job_type_id");

                    b.HasIndex("user_id");

                    b.ToTable("UserSkills");
                });

            modelBuilder.Entity("EntityLayer.Concrete.Users", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<int?>("address_id")
                        .HasColumnType("int");

                    b.Property<DateTime?>("date_birth")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("end_date")
                        .HasColumnType("datetime2");

                    b.Property<string>("explanation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("gender")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("job_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("link")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("mail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("major")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("note")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("phone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("photo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("school_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("start_date")
                        .HasColumnType("datetime2");

                    b.Property<string>("surname")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.HasIndex("address_id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("EntityLayer.Concrete.Categories", b =>
                {
                    b.HasOne("EntityLayer.Concrete.Users", null)
                        .WithMany("Categories")
                        .HasForeignKey("Usersid");

                    b.HasOne("EntityLayer.Concrete.Competencies", "Competencies")
                        .WithMany()
                        .HasForeignKey("competence_id");

                    b.Navigation("Competencies");
                });

            modelBuilder.Entity("EntityLayer.Concrete.Companies", b =>
                {
                    b.HasOne("EntityLayer.Concrete.Adresses", "Adresses")
                        .WithMany("Companies")
                        .HasForeignKey("address_id");

                    b.Navigation("Adresses");
                });

            modelBuilder.Entity("EntityLayer.Concrete.Competencies", b =>
                {
                    b.HasOne("EntityLayer.Concrete.JobApplications", "JobApplications")
                        .WithMany("Competencies")
                        .HasForeignKey("job_id");

                    b.Navigation("JobApplications");
                });

            modelBuilder.Entity("EntityLayer.Concrete.JobAdverts", b =>
                {
                    b.HasOne("EntityLayer.Concrete.Companies", "Companies")
                        .WithMany("JobAdverts")
                        .HasForeignKey("company_id");

                    b.Navigation("Companies");
                });

            modelBuilder.Entity("EntityLayer.Concrete.JobApplications", b =>
                {
                    b.HasOne("EntityLayer.Concrete.JobAdverts", "JobAdverts")
                        .WithMany("JobApplications")
                        .HasForeignKey("job_id");

                    b.HasOne("EntityLayer.Concrete.Users", "Userss")
                        .WithMany("JobApplications")
                        .HasForeignKey("user_id");

                    b.Navigation("JobAdverts");

                    b.Navigation("Userss");
                });

            modelBuilder.Entity("EntityLayer.Concrete.JobSkills", b =>
                {
                    b.HasOne("EntityLayer.Concrete.Users", null)
                        .WithMany("JobSkills")
                        .HasForeignKey("Usersid");

                    b.HasOne("EntityLayer.Concrete.Categories", "Categories")
                        .WithMany("JobSkills")
                        .HasForeignKey("category_id");

                    b.HasOne("EntityLayer.Concrete.Competencies", "Competencies")
                        .WithMany("JobSkills")
                        .HasForeignKey("compet_id");

                    b.HasOne("EntityLayer.Concrete.JobTypes", "JobTypes")
                        .WithMany("JobSkills")
                        .HasForeignKey("job_type_id");

                    b.HasOne("EntityLayer.Concrete.JobAdverts", "JobAdverts")
                        .WithMany("JobSkills")
                        .HasForeignKey("jobadvert_id");

                    b.Navigation("Categories");

                    b.Navigation("Competencies");

                    b.Navigation("JobAdverts");

                    b.Navigation("JobTypes");
                });

            modelBuilder.Entity("EntityLayer.Concrete.JobTypes", b =>
                {
                    b.HasOne("EntityLayer.Concrete.Users", null)
                        .WithMany("JobTypes")
                        .HasForeignKey("Usersid");
                });

            modelBuilder.Entity("EntityLayer.Concrete.UserSkills", b =>
                {
                    b.HasOne("EntityLayer.Concrete.Categories", "Categories")
                        .WithMany("UserSkills")
                        .HasForeignKey("category_id");

                    b.HasOne("EntityLayer.Concrete.Competencies", "Competencies")
                        .WithMany("UserSkills")
                        .HasForeignKey("compet_id");

                    b.HasOne("EntityLayer.Concrete.JobTypes", "JobTypes")
                        .WithMany("UserSkills")
                        .HasForeignKey("job_type_id");

                    b.HasOne("EntityLayer.Concrete.Users", "Userss")
                        .WithMany("UserSkills")
                        .HasForeignKey("user_id");

                    b.Navigation("Categories");

                    b.Navigation("Competencies");

                    b.Navigation("JobTypes");

                    b.Navigation("Userss");
                });

            modelBuilder.Entity("EntityLayer.Concrete.Users", b =>
                {
                    b.HasOne("EntityLayer.Concrete.Adresses", "Adresses")
                        .WithMany("Userss")
                        .HasForeignKey("address_id");

                    b.Navigation("Adresses");
                });

            modelBuilder.Entity("EntityLayer.Concrete.Adresses", b =>
                {
                    b.Navigation("Companies");

                    b.Navigation("Userss");
                });

            modelBuilder.Entity("EntityLayer.Concrete.Categories", b =>
                {
                    b.Navigation("JobSkills");

                    b.Navigation("UserSkills");
                });

            modelBuilder.Entity("EntityLayer.Concrete.Companies", b =>
                {
                    b.Navigation("JobAdverts");
                });

            modelBuilder.Entity("EntityLayer.Concrete.Competencies", b =>
                {
                    b.Navigation("JobSkills");

                    b.Navigation("UserSkills");
                });

            modelBuilder.Entity("EntityLayer.Concrete.JobAdverts", b =>
                {
                    b.Navigation("JobApplications");

                    b.Navigation("JobSkills");
                });

            modelBuilder.Entity("EntityLayer.Concrete.JobApplications", b =>
                {
                    b.Navigation("Competencies");
                });

            modelBuilder.Entity("EntityLayer.Concrete.JobTypes", b =>
                {
                    b.Navigation("JobSkills");

                    b.Navigation("UserSkills");
                });

            modelBuilder.Entity("EntityLayer.Concrete.Users", b =>
                {
                    b.Navigation("Categories");

                    b.Navigation("JobApplications");

                    b.Navigation("JobSkills");

                    b.Navigation("JobTypes");

                    b.Navigation("UserSkills");
                });
#pragma warning restore 612, 618
        }
    }
}
